apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - product-api.yml
  - product-api-service.yml
  - product-api-ingress.yml
images:
  - name: product-api
    newName: mirlock/product-api
    newTag: 221211.e1943e8