apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-api
  labels:
    app: product-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product-api
  template:
    metadata:
      labels:
        app: product-api
    spec:
      containers:
      - name: product-api
        image: mirlock/product-api:latest
        ports:
          - containerPort: 7001
        env:
          - name: ConnectionStrings:MongoDb:Uri
            value: mongodb://mongo-container:27017
            
          - name: ConnectionStrings:MongoDb:DatabaseName
            value: PetFriends